### ISSUE TITLE
Lambda returned an invalid option: 0.7 kW

### ISSUE THREAD

**Issue by Andrik45719** [dentra/esphome-ewh#13]
After last update preset mode not shown correctly in HA.
Any preset reset to 0.7 kW
EWH power sets correctly but HA card shows first item of list '0.7 kW'

[09:53:35][E][template.select:045]: Lambda returned an invalid option: 0.7 kW

[09:59:35][E][template.select:045]: Lambda returned an invalid option: 1.3 kW

**Comment by Djavdeteg** [comment]
Подтверждаю, только у меня Lambda returned an invalid option: 1.2 kW, как и выставлено на самом бойлере.

**Comment by Andrik45719** [comment]
Fixed: Clean Build Files && Install
