### ISSUE TITLE
Firmware compiling error

### ISSUE THREAD

**Issue by creasoftua** [dentra/esphome-ewh#4]
There is an error when compiling .bin from YAML config in ESPHome 
______________________________________________________________________________

Compiling /data/zanussi-artendo-pro/.pioenvs/zanussi-artendo-pro/src/esphome/components/ewh/climate/ewh_climate.cpp.o
In file included from src/esphome/components/ewh/climate/ewh_climate.h:10,
                 from src/esphome/components/ewh/climate/ewh_climate.cpp:3:
src/esphome/components/ewh/climate/../ewh_component.h:5:10: fatal error: esphome/components/text_sensor/text_sensor.h: No such file or directory
    5 | #include "esphome/components/text_sensor/text_sensor.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [/data/zanussi-artendo-pro/.pioenvs/zanussi-artendo-pro/src/esphome/components/ewh/climate/ewh_climate.cpp.o] Error 1

_____________________________________________________________________________

**Comment by creasoftua** [comment]
Uncommenting string "clock: github://dentra/esphome-ewh/ewh-pkg-clock.yaml@$ewh_version" in ewh.yaml resolved this issue

**Comment by dentra** [comment]
Yes, you can uncomment clock/timer or just add any template text_sensor with internal=true
