### ISSUE TITLE
при попытке обновить esphome на последнюю версию выдает ошибку

### ISSUE THREAD

**Issue by djvariado** [dentra/esphome-ewh#7]
при попытке обновить esphome на последнюю версию выдает ошибку
о том что параметр restore_state: true в ветке ewh-pkg-cloud.yaml не верен, мне удалось обновить заменив его на restore_mode: DISABLED

**Comment by dentra** [comment]
спасибо, взял в работу

**Comment by dentra** [comment]
в мастере
