### ISSUE TITLE
При компиляции в Home Assistant ругается на text_sensor

### ISSUE THREAD

**Issue by Djavdeteg** [dentra/esphome-ewh#8]
ESPHome 2023.7.0
При компиляции в Home Assistant ругается на text_sensor:

`Compiling /data/water-heater/.pioenvs/water-heater/src/esphome/components/ewh/ewh_utils.cpp.o
In file included from src/esphome/components/ewh/climate/ewh_climate.h:10,
                 from src/esphome/components/ewh/climate/ewh_climate.cpp:3:
src/esphome/components/ewh/climate/../ewh_component.h:5:10: fatal error: esphome/components/text_sensor/text_sensor.h: No such file or directory
    5 | #include "esphome/components/text_sensor/text_sensor.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [/data/water-heater/.pioenvs/water-heater/src/esphome/components/ewh/climate/ewh_climate.cpp.o] Error 1
In file included from src/esphome/components/ewh/ewh_component.cpp:4:
src/esphome/components/ewh/ewh_component.h:5:10: fatal error: esphome/components/text_sensor/text_sensor.h: No such file or directory
    5 | #include "esphome/components/text_sensor/text_sensor.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [/data/water-heater/.pioenvs/water-heater/src/esphome/components/ewh/ewh_component.cpp.o] Error 1`

Добавил в yaml после секции Substitutions: строку text_sensor:, вроде собралось.

Для Electrolux  Maximus wifi пришлось поменять пины TX и RX, все заработало.

Спасибо.

**Comment by dentra** [comment]
Обновление в мастере
